language: node_js
node_js:
  - "8"
addons:
  firefox: latest
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
before_install:
  - export XSTR_VERSION=$(node -p "require('./package.json').version")
script:
  - npm run lint
  - npm run test
  - npm run e2e
before_deploy:
  - echo "before deploy steps"
